menu:
  Home: /
  Archives: archives
  cate: cate
  page:
    归档: archives
    专题: categories
    友链: friendlinks
    关于: life
    搜索: search

sidePic: https://tva1.sinaimg.cn/large/007S8ZIlgy1ggdmi6yapmj30dw0zk0wm.jpg
avatar: https://tva1.sinaimg.cn/large/007S8ZIlgy1ggdmr1k3k0j305k05k74j.jpg

excerpt_link: 继续阅读
excerpt: 200

social:
  twitter: true
  github: true
  weibo: false
  yuque: true
  rss: true

twitter:
  username:

github:
  username:

weibo:
  username:

yuque:
  username:

# https://www.leancloud.cn/
valine:
  appId:
  appKey:

# https://web.umeng.com/
umeng: 1276809529
